name: SimpleBroadcast
api: [3.0.0]
main: RafmexHD\SimpleBroadcast\Main
version: 1.0
commands:
  broadcast:
    description: "Broadcast a Message"
    aliases: ["bcast", "bc"]
permissions:
  bcast.use:
    default: op
