name: SimpleBroadcast
api: [3.0.0]
main: RafmexHD\SimpleBroadcast\Main
version: 1.1
commands:
  broadcast:
    description: "Broadcast a Message"
    aliases: ["bcast", "bc"]
permissions:
  broadcast.cmd.bcast:
    default: op
